### ISSUE TITLE
[TODO] Implement open house mode

### ISSUE THREAD

**Issue by BertvanHoekelen** [loqed-nl/homey-app#5]
When the open house mode setting can be changed with the API.

- A new `open_house_mode` [capability](https://github.com/loqed-nl/homey-app/blob/master/.homeycompose/capabilities/lock_state.json) should be created.
- The api should be called with the new `open_house_mode` capability when it's changed.
- The `open_house_mode` capability should be updated through a webhook when it's changed from the loqed app.

## Progress
- [x] Open house mode enabled/disabled trigger (polling)
- [x] Open house mode using webhook
- [x] Enabled/disabling open house mode using homey

**Comment by hansallis** [comment]
I've been looking at this a bit, but seems that the app enabled/disables this through grpc. I've tried to reverse engineer this by using a socks proxy on my iphone, but the connection doesn't even show up. I wiresharked (wireshurk, what's the past tense?) the connection, but can't decrypt the TLS obviously. If I'm bored enough I'll go the extra mile and use DNS spoofing and then see if it accepts my own certificate.

Or maybe I'm missing a much easier route. Any info is welcome :)

**Comment by ElStupid** [comment]
Maybe Fiddler could work for you?
https://www.telerik.com/blogs/how-to-capture-android-traffic-with-fiddler
I know you have iPhone, maybe there's more info on that too

**Comment by hansallis** [comment]
Thanks, fiddler sounds somewhat similar to the proxy I setup. Trying Android is a good idea though; maybe the Android app won't go around the proxy and allow me to look at the data going over the wire.

**Comment by BertvanHoekelen** [comment]
We will wait for the official API implementation to support this in the LOQED homey app.

**Comment by BertvanHoekelen** [comment]
I added a "open house enabled/disabled" trigger in version 3.3.0. This is currently working using polling, we are investigating updating this using a webhook. We are also looking into enabling open house mode using Homey. I will track the progress in this issue.

**Comment by wesley3210** [comment]
Hi Bert,

I am also interested in tis function, open house mode activation in Homey, so I can use it on my dashboard. When children playing outside, we do’nt need the app but we can touch the activate button on our dashboard.
Do you know of this function will be available soon?

Thanks!

**Comment by wdool** [comment]
Loqed support (Mike) great guy!! suggested to report this issue here:
I had this issue, wanted to solve this but didn’t succeed… Also had a engine replacement and thus a new lock, new install and repair suggestion, had it all… Handed in a support request at Loqed…


![IMG_9205](https://github.com/loqed-nl/homey-app/assets/35030791/ef1c16bb-7349-4cf6-87ab-5a57f6460591)

**Comment by XeroxQ** [comment]
Available in the current live version
